# Datos de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda
spring.datasource.username=postgres
spring.datasource.password=1234

# Configuración de Hibernate (JPA)
# 'update' hará que Java cree las tablas si no existen o las actualice si agregas campos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Configuración para envío de correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eviljjmz@gmail.com
spring.mail.password=msru fkzs jcxq yzhq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true